- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the product count
  ansible.builtin.shell:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: produt_count
  when: component == "catalogue"

- name: get the user count
  ansible.builtin.shell:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: component == "user"

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: "load product data"
  ansible.builtin.shell: "mongo --host mongodb.daws76s.online < /app/schema/{{component}}.js"
  when: product_count.stdout == "0" and componenr == "catalogue" # keep double quotes
  ignore_errors: true

- name: "load user data"
  ansible.builtin.shell: "mongo --host mongodb.daws76s.online < /app/schema/{{component}}.js"
  when: user_count.stdout == "0" and component == "user" # keep double quotes
  ignore_errors: true
  